export enum ActionTypes {
  FETCH_USERS_START = "CREATE_DIALOG:FETCH_USERS_START",
  FETCH_USERS_SUCCESS = "CREATE_DIALOG:FETCH_USERS_SUCCESS",
  FETCH_USERS_FAIL = "CREATE_DIALOG:FETCH_USERS_FAIL",
  FILTER = "CREATE_DIALOG:FILTER",
}