export enum ActionTypes {
  AUTH_START = "AUTH:AUTH_START",
  AUTH_FAIL = "AUTH:AUTH_FAIL",
  REGISTRATION_SUCCESS = "AUTH:REGISTRATION_SUCCESS",
  LOGIN_SUCCESS = "AUTH:LOGIN_SUCCESS",
  LOGOUT = "AUTH:LOGOUT",
  FETCH_USER_START = "AUTH:FETCH_USER_START",
  FETCH_USER_SUCCESS = "AUTH:FETCH_USER_SUCCESS",
  FETCH_USER_FAIL = "AUTH:FETCH_USER_FAIL",
}