FROM ubuntu:bionic

ENV DIR=/home/as

WORKDIR $DIR

RUN  apt-get update -y && \
  apt-get upgrade -y && \
  apt-get dist-upgrade -y && \
  apt-get -y autoremove && \
  apt-get clean

RUN apt-get install -y zip \
  unzip \
  && rm -rf /var/lib/apt/lists/*

COPY ./app.zip $DIR/app.zip

RUN unzip -q $DIR/app.zip
RUN rm $DIR/app.zip
RUN chmod +x ./app
RUN ls

ENTRYPOINT ["./app"]
