export default {
  JOIN_ROOM: "CHAT:JOIN_ROOM",
  SEND_MESSAGE: "CHAT:SEND_MESSAGE",
  DELETE_MESSAGE: "CHAT:DELETE_MESSAGE",
  CREATE_DIALOG: "CHAT:CREATE_DIALOG",
  DELETE_DIALOG: "CHAT:DELETE_DIALOG",
};