export enum ActionTypes {
  FETCH_USERS_START = "CREATE_DIALOG_USERS:FETCH_USERS_START",
  FETCH_USERS_SUCCESS = "CREATE_DIALOG_USERS:FETCH_USERS_SUCCESS",
  FETCH_USERS_FAIL = "CREATE_DIALOG_USERS:FETCH_USERS_FAIL",
}